input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        [1, Conv , [32, 3, 2]],
        [1,MBConv,[16, 1, 3, 1]],
        [2,MBConv,[24,6,3,2]],
        [2,MBConv,[40,6,5,2]],
        [3,MBConv,[80,6,3,2]],
        [3,MBConv,[112,6,5,1]],
        [4,MBConv,[192,6,5,2]],
        [1,MBConv,[320,6,3,1]],
        [1, Conv, [1280, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Flatten, []],
        [1, Linear, [9]],
    ]